### ISSUE TITLE
Output csv file is empty

### ISSUE THREAD

**Issue by feldmanz66** [m8r0wn/pymeta#5]
When I run pymeta, its discovering files properly however the output csv file is empty. Someone mentioned that the issue was from Harvey's exiftool and the solution was to apt-get install it. However it looks like it already exists in pymeta resources folder which seems like it shouldn't need to be installed then.

Can you help identify what the issue is. I was able to reproduce this on a lambda in python runtime (cant install exiftool) along with on a macbook pro. 

The test command I'm running is `python3 ./pymeta/pymeta.py -d example.com -o ./output/my.csv`.

**Comment by feldmanz66** [comment]
Closing because the ExifTool needs to be installed. This should be marked as a hard dependency as it looks for the image on line 35 of `resources/exiftool`

**Comment by feldmanz66** [comment]
Closing because the ExifTool needs to be installed. This should be marked as a hard dependency as it looks for the image on line 35 of `resources/exiftool`

**Comment by m8r0wn** [comment]
Hi @feldmanz66,

Appreciate your follow up on this, Ill check it out and see if i can recreate the issue. When developing, I testing on both Kali and ubuntu without any issues.

\- m8r0wn
